# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # Concrete types only for type checkers; at runtime these become `object`
    VERSION_TUPLE = tuple[int | str, ...]
    COMMIT_ID = str | None
else:
    VERSION_TUPLE = object  # type: ignore[assignment]
    COMMIT_ID = object  # type: ignore[assignment]

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID

# Keep whatever your build system wrote here; examples:
# __version__ = version = "2.0.5"
# __version_tuple__ = version_tuple = (2, 0, 5)
# If your tooling injects a dev version, leave it as-is.

__version__ = version = "2.0.5"
__version_tuple__ = version_tuple = (2, 0, 5)

__commit_id__ = commit_id = None
